// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzcYVz0tLzRJTx1SOBb444QaolQiOByn0',
    appId: '1:293793968664:web:dbca84945bf1ad450a496d',
    messagingSenderId: '293793968664',
    projectId: 'fir-firbase-735bc',
    authDomain: 'fir-firbase-735bc.firebaseapp.com',
    storageBucket: 'fir-firbase-735bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwma0GOUZUfeH7eUGaIkuc0QjMdLQO7Xg',
    appId: '1:293793968664:android:0ec31e1053e5c4390a496d',
    messagingSenderId: '293793968664',
    projectId: 'fir-firbase-735bc',
    storageBucket: 'fir-firbase-735bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5P7W5b-T1W1MH_4rYF9ptA8JkIEqEj8',
    appId: '1:293793968664:ios:26679c8dd5555fd20a496d',
    messagingSenderId: '293793968664',
    projectId: 'fir-firbase-735bc',
    storageBucket: 'fir-firbase-735bc.appspot.com',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5P7W5b-T1W1MH_4rYF9ptA8JkIEqEj8',
    appId: '1:293793968664:ios:26679c8dd5555fd20a496d',
    messagingSenderId: '293793968664',
    projectId: 'fir-firbase-735bc',
    storageBucket: 'fir-firbase-735bc.appspot.com',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzcYVz0tLzRJTx1SOBb444QaolQiOByn0',
    appId: '1:293793968664:web:e2d4b87123b8f7ab0a496d',
    messagingSenderId: '293793968664',
    projectId: 'fir-firbase-735bc',
    authDomain: 'fir-firbase-735bc.firebaseapp.com',
    storageBucket: 'fir-firbase-735bc.appspot.com',
  );
}
